### ISSUE TITLE
lzop remains zombie <defunct> on every script restart

### ISSUE THREAD

**Issue by ckir** [afshinrahimi/twitter-fetcher#2]
Use ps command to see it.

You can use

import signal
signal.signal(signal.SIGCHLD, signal.SIG_IGN)

to avoid it

Also it will be nice to add KeyboardInterrupt and sigterm handlers

**Comment by afshinrahimi** [comment]
Nice catch Costas.
 I'll have time next week to test it and commit it. Meanwhile if you had time to resolve and test the issue, you can submit a pull request.
Cheers.

**Comment by cschwem2er** [comment]
Hi,
I just found this repo via [stackoverflow](http://stackoverflow.com/questions/23601634/how-to-restart-tweepy-script-in-case-of-error), thanks for putting it up! Keyboard Interrupt would be awesome :)

**Comment by afshinrahimi** [comment]
Nice to see people looking at it. I'll try to put the keyboardinterrupt and also the child signal ASAP.

**Comment by afshinrahimi** [comment]
keyboardInterrupt added.
the script kills lzop when quitting so no more dummy lzop.
